version: '2'
services:

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ~/.docker-mysql:/var/lib/mysql

  web:
    build: .
    command: bin/rails server --port 3000 --binding 0.0.0.0
    links:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/rails-test

  wordpress:
    image: wordpress
    ports:
      - "8080:80"
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_PASSWORD=password
    links:
      - db
    volumes:
      - ~/.docker-wordpress:/var/www/html  