version: '2'
services:

  db_host:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ~/.docker-mysql:/var/lib/mysql

  web:
    build: .
    command: bin/rails server --port 3000 --binding 0.0.0.0
    links:
      - db_host
    ports:
      - "3000:3000"
    volumes:
      - .:/rails-test